### ISSUE TITLE
`.py` not `.ipynb` for smaller file sizes.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#120]
Hi all,
I discovered a most excellent thing recently; Jupyter can open `.py` files like `.ipynb` files. Typically I avoid using `.ipynb` with `git` because it is an endless source of merge conflicts. For example if two people just run the same script on different branches it creates a merge conflict because the execution number of the cells is different. Moreover, these merge conflicts are annoying because you have to sift through an ungodly amount of `.json` making it hard to tell when actual code has been changed. In my experience there is also no syntax highlighting making it even more frustrating. No longer, I would be highly in favour of transferring our `.ipynb` files into `.py` files and running them as notebooks. The downside is that the final execution state is not saved but I do not see this as much of a problem. 
Anyway let me know what you think,
Regards
Jordan

**Comment by ataras2** [comment]
Strongly agree! A few things:

1. Once done, the .ipynb should all be purged from the past commits so the clone time decreases drastically and people can get started faster
2. The change should be made explicit in the docs since a lot of our users will look for .ipynb 
3. (Windows users) I'm not sure if google colab can open the same way Jupyter can, at a glance it doesn't. We can, however, make our own google colab sharable links (e.g. see top of https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial11/NF_image_modeling.html). Sharable links might even make it easier since people don't need to clone to try dLux out.

**Comment by ataras2** [comment]
Strongly agree! A few things:

1. Once done, the .ipynb should all be purged from the past commits so the clone time decreases drastically and people can get started faster
2. The change should be made explicit in the docs since a lot of our users will look for .ipynb
3. (Windows users) I'm not sure if google colab can open the same way Jupyter can, at a glance it doesn't. We can, however, make our own google colab sharable links (e.g. see top of https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial11/NF_image_modeling.html). Sharable links might even make it easier since people don't need to clone to try dLux out.

**Comment by benjaminpope** [comment]
We need them in the docs, because they need to render all of their outputs. We don't need them elsewhere.

**Comment by LouisDesdoigts** [comment]
> Jupyter can open .py files like .ipynb files.

How do you do this, can you show an example? I'm definitely a fan of reducing the package size and removing the notebooks is the way to go, but I couldn't find anything online really.

Also *most* of the notebooks that do exist will be turned into docs tutorials, which as Ben said need to be notebooks. That said the science/ and sandbox/ directories do have stuff that I need to move into other repos, but that has just been low on the priority list.

**Comment by Jordan-Dennis** [comment]
I just run 
```
jupyter notebook
```
and then click on the `.py` file and it opens. It saves with `#+` and `#-` comments where the breaks are. 

If they will be going to other repositories then we probably do not need to worry about it too much.

**Comment by LouisDesdoigts** [comment]
Most notebooks have been removed, and we will implement tutorials as .md files in the future, not as .py files.
