### ISSUE TITLE
Optimisation in `MuliAperture`.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#152]
Hi all,
I think we can optimise the `__call__` method of the `MultiAperture` by using a `for` loop and `if` statment instead of entering the `__call__` method of the children.

**Comment by LouisDesdoigts** [comment]
Yeah so just had a little peek through the code there, we don't want to actually use a for loop there because the calculation is not markovian it can all be done simultaneously. This is where we would want to apply `jax.tree_map` to the dictionary of apertures, using the `is_leaf` input to optionally call or not call the methods of specific layers.

**Comment by benjaminpope** [comment]
Yes - the more we use `jax` map functionality, the better this will scale to GPU and HPC environments.

**Comment by Jordan-Dennis** [comment]
Has the difference been profiled? From the stack trace I know that `jax.tree_map` uses list comprehensions under the hood so I would be surprised if there was a massive difference.
