### ISSUE TITLE
Generate `Wavefront` Coordinates at `__init__` Time.

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#177]
Hi all, 
The `wavefront.pixel_coordinates` method is regenerating the coordinates grid every time it is accessed. I see no reason we cannot just make the coordinates a property of the wavefront. 
Let me know your thoughts,
Jordan

**Comment by LouisDesdoigts** [comment]
It needs to be generated at run time because the properties of the wavefront change throughout the propagation so the coordinates are changing too. 

It similarly prevents cluttering of the wavefront class when examining, and prevents having multiple parameters track the same value (ie pixelscale and npix are entirely equivalent to the coordinate system)

**Comment by Jordan-Dennis** [comment]
Pain in the arse that.
