### ISSUE TITLE
Development of optical components layer script

### ISSUE THREAD

**Issue by LouisDesdoigts** [LouisDesdoigts/dLux#59]
So we want to support arbitrary optical systems configurations. This would mean constructing a set of very general layers for common optical components, ie lenses, phase plates, etc. @Jordan-Dennis has made a start on a structure for this script which looks rather good. In the long run we could build a minimal web-scraper to map specific optical components like [this](https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=12767) to their exact chromatic response and manufacturer specifications. 

Integration with manufacturers is probably a unnecessary long-term goal, but the basic optical components script is desired.

**Comment by Jordan-Dennis** [comment]
So my initial thoughts are included below. This is what @LouisDesdoigts and I originally discussed:
```py
class Layer(eqx.Module):
    def __call__(self, parameters): # abstract

class CurvedOptic(Layer):
    def _curvature(self): # abstract

class Mirror(Layer):
    def _reflect(self, wavefront): # abstract
    def __call__(self, parameters): # concrete

class GaussianMirror(CurvedOptic, Mirror):
    def _curvature(self): # concrete
    def _reflect(self, wavefront): # concrete

class HyperbolicMirror(CurvedOptic, Mirror):
    def _curvature(self): # concrete
    def _reflect(self, wavefront): # concrete

class SphericalMirror(CurvedOptic, Mirror):
    def _curvature(self): # concrete
    def _reflect(self, wavefront): # concrete

class Lens(CurvedOptic):
    index_of_refraction : float 
    def _curvature(self): # abstract
    def _focus(self, wavefront): # concrete
    def __call__(self, parameters): # concrete

class GaussianLens(Lens):
    def _curvature(self): # concrete

class HyperbolicLens(Lens):
    def _curvature(self): # concrete 

class ParabolicLens(Lens):
    def _curvature(self): # concrete

class Aperture(Optic):
    def _area(self): # Still abtract 
    def __call__(self): # concrete

class CircularAperture(Aperture):
    radius : float
    def _area(self, wavefront):

class RegularPolygonalAperture(Aperture):
    number_of_sides : int
    radius : float
    def _area(self): # concrete

class ArbitraryAperture(Aperture):
    binary_mask : int
    def _area(self):
        return self.binary_mask

class PhasePlate(Optic):
    def _phase_shift(self): # abstract
    def __call__(self): # concrete

class ArbitraryPhasePlate(Optic):
    phase : array
    def _phase_shift(self):
        return self.phase

class ChromaticPhasePlate(Optic):
    def _phase_shift(self, wavefront): # concrete
        # dependence on wavelength 
```
Although I was thinking about #60 and thought we could extend this even further by adding:
```py
class Source(Layer): # abstract
    def _create_wavefront(self): # abstract
    def __call__(self, parameters): # concrete

class CoherentPointSource(Layer):
    def _create_wavefront(self): # concrete

class CoherentPlaneSource(Layer): # Point source at infinty?
    def _create_wavefront(self): # concrete
```
where there are many other sources that could be generated. This leads to the natural extension of `CreateWavefront` into a set of many simple layers with specific properties. To me, it makes most sense to have `CoherentPointSource` output an `AngularWavefront` since the `Wavefront` is spherical and is best described by a field of view. `CoherentPlaneSource` on the other hand is better suited to a `PhysicalWavefront`. `GaussianWavefront` is a bit trickier because it requires a `Lens` or `Mirror` with a curvature.

**Comment by Jordan-Dennis** [comment]
The main idea behind the `Source` was to give a physical interpretation for `CreateWavefront` allowing natural extension to `CreateAngularWavefront`, `CreateGaussianWavefront` ect. but I think that #60 has moved beyond this now.

**Comment by LouisDesdoigts** [comment]
Yeah also if we conceptualise a source class then that inherently tangles positions, wavelengths and fluxes directly into that class. That will create a MUCH more complicated structure with data living/being defined in multiple places (OpticalSystem and Source). Don't lose sight of the goal here, we're not creating an optical simulation framework, that already exists - We're create an autodiff optical simulation framework. That should be one of the primary considerations whenever we do anything, and we should never create things that serves to complicate that outcome (which I think a `Source` class would).

**Comment by Jordan-Dennis** [comment]
Hi all,
while developing the `HexagonsAndHexikes` I have started some early work on this as both the `BasisPhase` (name subject to change) and `HexagonalAperture` needed are parts of this structure. As a result it did not make sense to retro-fit them only to have to update them onto the newer structure at a soon and later date. Everything is currently in the `dev/layers.py` file and I would love early feedback to changes to reduce workload later on. As normal I've gone "full steam", `abstractmethod`s, `cached_property`s ect. because it is normally easier to remove these things than to add them, so in particular I would like feedback on how much to keep. 
Regards
Jordan

**Comment by ataras2** [comment]
Made a little UML for this
![image](https://user-images.githubusercontent.com/42081503/178905888-0a608853-4a64-4536-a92b-1203ae284327.png)
I think several smaller diagrams for user facing classes could streamline documentation. Do you think they need the class methods?

**Comment by LouisDesdoigts** [comment]
Nice this is great @ataras2. I agree that the documentation is in more of a 0.x state and I think these diagrams are going to be key in taking us to some 1.x docs.

I think the decisions to include the class methods will have to be on a case-by-case basis, some layers will have useful, user-facing methods (ie ApplyBasisCLIMB has a 'get_binary_phase()' method so you can actually see the mask its using), but others really don't need any (ApplyAperture has nothing beyond __init__ and __call__).

I also think in the long run that this will be informed by #65, so I think for now everything is where it needs to be.
