### ISSUE TITLE
`Image` Class to Reduce repetition

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#62]
Hi all,
A large number of classes store pixel arrays a.k.a images. There is certain functionality that is associated with this, for example the generation of para-axial arrays. I have tried to keep the naming consistent but we have `Propagator._get_pixel_grid` and `Wavefront.get_pixel_positions` which do the same thing. There is the option to make `Wavefront.get_pixel_positions` an `@staticmethod` with `npix` as a parameter. 

Aside: A static method does not require the class to instantiate an object and can literally be called like `Wavefront.get_pixel_positions(npix)`.

While this is probably the neatest solution at present it does not make much physical sense. Why should the wavefront describe that behaviour? However, I do think we should include the logic of the function in only one place. I think this because `Propagator` and `Wavefront` actually defined the para-axial centre differently and when I discussed this with @LouisDesdoigts we decided that it was a bug. Additionally, some `Layer` classes, use this functionality, for example the `CircularApperture`. 

The typical OOP solution is to build a class `Image` or `ImageHolder` that the other classes can inherit from (thankfully python supports multiple inheritance). This would hold the parameter `_image : Array` and define a series of useful methods. 
```py
class Image():
    _image : Array
    
    # NOTE: names are not final, just suggestions
    def get_pixel_coordinates() -> Vector: # Along edge
    def get_pixel_positions() -> Tensor: # 2 stacked grids in 3rd order tensor 
    def get_radial_positions() -> Matrix: # stacked grid
```
The downfall of this is that you get a very complicated class hierarchy (still quite simple in our case), which is the general downfall of OOP. 

A further option is to register all the methods of the class I describe above as `@staticmethods` making the nearest thing to a static class python provides. With reference to #58 this could go into `src/utilities/image.py` and then usage would be through `Image.get_pixel_coordinates(npix)` ect. 

I quite like the idea of implementing such a static class, because it also avoids subclasses ending up with lots of methods that they never use as can happen with OOP programming. 

As always let me know what you think.

Regards

Jordan

**Comment by Jordan-Dennis** [comment]
A further option is of course to define these as functions in a file like `helpers.py` and import them one by one as needed. I've started an implementation of the static class approach on the `HexagonsAndHexikes` branch which I think will turn into a demo branch for a lot of the outstanding issues and discussions, since things like the `HexagonalAperture` will be best implemented in the struture discussed in #59.

**Comment by ataras2** [comment]
Have we considered a different relation other than inheritance? At a glance, it makes more sense to me for it to be `Wavefront ` "has a" (composition) `Image ` rather than `Wavefront` "is a" (inheritance) `Image`

**Comment by LouisDesdoigts** [comment]
Yeah so I definitely think we want to lift the get_pixel_coordinates() out of the wavefront class, they were initially most used there, but clearly since we define everything as paraxial these are actually package-wide definitions. I don't know where exactly these should live (see #58), but its becoming obvious that these are generic methods defining the optical axis should be consistently available across the whole package.

I propose we 'merge' this issue with #58, and put that code in the src/optics/helpers.py script or something similar. That script would then house the other optics-focused function: opd_to_phase/phase_to_opd, get_pix_per_fringe, arcsec_to_rad/rad_to_arcsec etc. 

We would probably want to re-name them though, maybe something along the line of:
`get_paraxial_coords()` which calls `get_paraxial_pixels()` which calls `get_paraxial_vector()`. This would allow us to define the optical axis consistently across the whole package and probably save a lot of trouble!

**Comment by Jordan-Dennis** [comment]
Sounds, good. How do you merge issues? As previously stated there is a demo for the static class I proposed available. Alternatively, like I said earlier one can just use these as functions (they are just slightly less grouped this way, but probably more friendly to `jax`). I also agree about the name change.

**Comment by LouisDesdoigts** [comment]
I also don't think we want to create an `Image` class. For one thing as we integrate with the JWST infrastructure we want to let them do as much of the work as possible (they have 4 separate and unique coordinate system and a whole (package)[https://pysiaf.readthedocs.io/en/latest/] just to manage this). In an ideal world we just port calls to poppy from webbpsf into ∂Lux and let their mammoth packages do all the annoying stuff.

**Comment by LouisDesdoigts** [comment]
> 

I don't think you can merge issue, will just have to close them together.

**Comment by Jordan-Dennis** [comment]
Cool, I'll move the functionality I create (as functions?) into `helper.py` :+1:

**Comment by Jordan-Dennis** [comment]
There is actually the question of normalisation (i.e. multiplication by `2 / npix`), this is very simple and can always be done in place. But, what if I want to get normalised radial coordinates. I believe that the scalar multiplication is still the correct normalisation but in the code the requires it, it is done at the `get_pixel_vector` level. 

To clarify `get_radial_coordinates * 2 / npix` is correct, but this is not obvious. Should we provide some sought of utility. One option might be `axial_normalise(get_radial_coordinates)(npix)`.

**Comment by LouisDesdoigts** [comment]
All that should just be generic optional args to the functions no? We may have to expand into a more than three functions but as long as they all use the same consistent definitions then everything should be fine.

**Comment by LouisDesdoigts** [comment]
I'll also just pop a link to #36 as a reminder as to why we don't want to do detector/image class stuff ourselves 😅

**Comment by benjaminpope** [comment]
I should add - we definitely want to build this around a use case where a typical JWST source is 
- one or more point sources, superimposed over 
- a pixel grid representation of something like a disk or a spiral, in RA and Dec coordinates, usually much fainter than the point source
- a distortion map from RA, Dec to x, y

We will then want to learn 
- the positions and fluxes (and colours*?) of these point sources
- the intensity map and probably a uniform colour of the pixel grid image

* by colour I mean a low-dimensional representation of the spectrum - typically we might just want to consider the slope of the spectrum across the filter bandpass

So it is important that we not to try to include the point source(s) in the pixel map - otherwise we can't place them accurately enough - and that we preserve the capacity to have different colours in the background (a circumstellar disk will typically be redder than the star, while a galaxy behind a quasar, god knows!)

**Comment by Jordan-Dennis** [comment]
I thought I would pop a link to #59 based on your comment @benjaminpope. @LouisDesdoigts and I discussed a `Source` style structure but didn't want to duplicate where data was stored. Please leave a comment on that thread if you think we should reconsider a similar structure.
