### ISSUE TITLE
Notebooks need updating on layer internals

### ISSUE THREAD

**Issue by ataras2** [LouisDesdoigts/dLux#64]
Was trying to rerun [Instrument Calib](https://github.com/LouisDesdoigts/dLux/blob/main/notebooks/Instrumental_calibration.ipynb) and ran into errors in block 6, line 5 and had to change to `det_npix = lays[-1].pixels_out`. I suspect this isn't the only case. Going forward, maybe get/set methods could avoid some of this but at the moment I think reaching into the layer is fine.

**Comment by Jordan-Dennis** [comment]
I agree, we should probably have `get` and `set` methods. I believe they were left out because we did not want users being able to modify the state (`eqx.tree_at` isn't a friendly function to begin with). `layers.py` is in an early stage, #59 discusses the long term plan for the script.

**Comment by benjaminpope** [comment]
I think we don't want to resort to get and set methods - we want to stick to syntax as similar as possible to Equinox neural networks, for example https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/conv.py. 

The reason for this is if there is a significant Jax or Equinox update, we don't want things to break!

**Comment by LouisDesdoigts** [comment]
I mean the getter methods are trivial - its just a one line code wrapper so I would be horrendously surprised if that actually conflicted with anything. I also think the setter methods are crucial, going by the 'Peter test' it will be much easier to simply fix any problems than it will be to explain to Peter what a PyTree is and what a lambda function is 😅. Besides, its a single line wrapper to the same function call, I seriously doubt this could cause us trouble in the long run but it is a fair point.

**Comment by benjaminpope** [comment]
Sure... I just am cautious about introducing *any* syntax that isn't core Jax or Equinox, because we know how Jax versions move...

**Comment by Jordan-Dennis** [comment]
I thought I would use this thread to explain how (I think :laughing:) `equinox` works under the hood. Most of you probably know this already (perhaps more) but thought it would be good to all be on the same page (If you do know more, please add to this thread). 

`equinox` just registers the class as a PyTree by providing default implementations for `flatten` and `unflatten` (the names I used might not be correct) so that `Jax` can move the PyTree between `XLA` and Python. The real magic of `equinox` is that it let's us `jit` and `grad` with respect to certain attributes/fields of the class/PyTree. If our PyTree were a list; `[[1, 2], 1, 1] we can essentially take the gradient of an operation with respect to the nested `[1, 2]` _only_. For `jit` it just marks the other fields, i.e. `..., 1, 1]` as static arguments. Methods are registered as PyTree nodes (I believe, if they are registered at all) and so have no affect on this process. 

Curiously, the process also means that all class methods are actually registered as `tree_util.Partial` objects. @benjaminpope you may remember back in my early days me and Patrick had a discussion about this. Turns out he was way ahead all along as you may have expected. 

I think `set_` and `get_` methods are mostly just a convenience and tidy up the code. For example, the `update_phasor` in "pure" `equinox` is:
```py
wavefront = eqx.tree_at(lambda wavefront : wavefront.amplitude, self, amplitude, 
    is_leaf = lambda leaf : leaf is None)
wavefront = eqx.tree_at(lambda wavefront : wavefront.phase, self, phase, 
    is_leaf = lambda leaf : leaf is None)
```
where `phase` and `amplitude` are assumed to exist and the `is_leaf` argument allows equinox to tree `None` as a leaf which in default `JAX` is actually a node.
Assuming that `set_phase` and `set_amplitude` exist and wrap the `tree_at` syntax the `update_phasor` method becomes:
```py
self.set_amplitude(amplitude).set_phase(phase)
```
which is much more readable and concise. Due to the number of other functions that need to `set_` some property I support keeping them. As @LouisDesdoigts said they are just wrappers to pure `equinox` and `Partial` wrappers at that which means they are entirely implemented in `jax` and `equinox`. 

I think Patrick explores the idea of "parameterised functions" more, while we are looking more at the OOP capabilities. This is why I agree with @benjaminpope and @LouisDesdoigts for `layers.py` which are "parametrised functions" more than they are classes. Despite this I still think a class structure can be exploited to simplify this code although I am open to feedback based on the content of this discussion.
 
Sorry that was so long

Jordan

**Comment by LouisDesdoigts** [comment]
Hey @Jordan-Dennis this looks great and I love the idea of putting this info together. Maybe we could turn this into a discussions page, which can eventually be turned into some part of a tutorial with the on-boarding notebooks.

One thing I would say is that there was only ever one case that needed the `is_leaf = lambda leaf : leaf is None` syntax and that was for updating the Wavefront object in the CreateWavefront layer since the object is actually initialised in the OpticalSystem class with `None` values for wavefront size and pixel scale, and the default behavior for `eqx.tree_at` is to ignore None leaves. I would suspect we want to match this behavior unless its explicitly needed (such as in CreateWavefront) as `None` seems be an important class type in the equinox ecosystem.

**Comment by LouisDesdoigts** [comment]
Closing this issue as now all of the code used to run these notebooks previously now exists in the documentation notebooks, and the /notebooks folder has been removed
