### ISSUE TITLE
more default layers

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#88]
We should be able to specify telescope geometry more like in `poppy` - with spiders, secondaries, etc in premade layers.

**Comment by Jordan-Dennis** [comment]
:+1:, I'll just through a link to #59, where we have been discussing this somewhat. I think this will be something that I can do during semester (at least early on), since it is very modular. 

We should probably make a comprehensive list of the elements that we want to construct as a task list in this issue or #59.

**Comment by Jordan-Dennis** [comment]
So as part of the `dwarfs` project I will be adding, `Spiders` and some more `Apertures`. These have not hit `dLux` yet but are coming soon.

**Comment by benjaminpope** [comment]
Awesome. The more apertures we have in our library the easier it will be for our users (and you!).

**Comment by Jordan-Dennis** [comment]
OK so I am just correcting the `Aperture` branch code to work with the new version of `main`. Making some pretty pictures in the process that I thought were worth sharing :smile: :laughing: 
![image](https://user-images.githubusercontent.com/93350879/203876699-d832c24d-8f07-4de4-b601-e48201f625cf.png)
Hopefully we can get these onto `main` soon.

**Comment by benjaminpope** [comment]
Pretty pictures!
