### ISSUE TITLE
`PlaneType` vs `plane_type`

### ISSUE THREAD

**Issue by Jordan-Dennis** [LouisDesdoigts/dLux#89]
Hi all,
In the `poppy` version of the Lawrence et. al. Fresnel algorithm they automatically convert the units to angular in the image plane by keeping track of the `plane_type` with the `PlaneType` `enum`. I was wondering if we should consider using an `enum` ourselves, at the moment we are using `plane_type : str` which is fine as well. The advantage to using an `enum` is that it only has specific values, for example, `PlaneType.Image`, `PlaneType.Intermediate` and `PlaneType.Pupil`, whereas a `str` can have any value. Another advantage is that each entry can be associated with an integer which is useful for using `jax.lax.switch`. `enum` is part of the standard library so it wouldn't be an additional dependency.

Let me know your thoughts,

Jordan

**Comment by benjaminpope** [comment]
Yes `enum` sounds like a good plan.

**Comment by LouisDesdoigts** [comment]
So I just 'fixed' #60 in a basic way. We are going to want to fix it properly in the future using the same method as described here. I've closed the issue for now because in the future I believe we are going to want to fully instantiate Wavefront with all of their parameters (which I know you have wanted for a while now @Jordan-Dennis 😂).

Similarly I want to have a chat to @Jordan-Dennis about the best way to merge the GaussianWavefront class, as it defines beam_radius, which I believe is equivalent to pixel_scale in regular wavefront, so we should homogenise our definitions. 

I figured this would better to do as one big change after we're all on the same page, rather than making a bunch of small changes breaking things along the way.

**Comment by LouisDesdoigts** [comment]
Alright so I did some testing on this on the new 'Planetype' branch. It didn't seem to work, with the main error being `TypeError: Value <PlaneType.Pupil: 0> with type <enum 'PlaneType'> is not a valid JAX type`. This is the same error at the same place that I was having with #102, except with str, rather than enum. 

I did a bit more (brief) looking into jax and enum and I'm not so sure they will be compatible, although I haven't looked very hard or tested very much.

**Comment by LouisDesdoigts** [comment]
Alright so I was able to get the enum working for PlaneType! There is a small caveat though... Jax only works specifically with `enum.IntEnum` objects, which means that jax and therefore equinox sees it as an integer array and therefore turns it into an `i32[]` tracer. Equinox's default filter function for `filter_jit` is `eqx.is_array_like` which means that it tries to make it concrete and then throws a `ConcretizationTypeError` because its obviously a tracer. This can be trivially fixed by adding the `fn=eqx.is_inexact_array` argument to `eqx.filter_jit`.

This just means that by adding enum, we need to always pass in this extra argument to `filter_jit` which is a bit annoying. Ideally we could set this globally and I [posted and issue](https://github.com/patrick-kidger/equinox/issues/177) to Equinox to see if this is possible in the future. 

Essentially this change is ready to merge into main, unless you guys have strong feelings around this mild annoyance. Anyway let me know @Jordan-Dennis @benjaminpope
